server:
  port: 8082
spring:
  application:
    name: online-store-catalog
  datasource:
    url: jdbc:mysql://mysql:3306/productdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: online-store-catalog-group
