spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      locator:
        enabled: true
      enabled: true
    gateway:
      routes:
        - id: event-service
          uri: lb://event-management-system
          predicates:
            - Path=/event/**
        - id: product-service
          uri: lb://online-store-catalog
          predicates:
            - Path=/product/**
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true
